import { WorkoutLog, MealEntry, BiometricState, CommunityPost, FitnessGoal, DailyNutritionTarget } from './types';

export const initialNutritionTarget: DailyNutritionTarget = {
  calorieTarget: 2450,
  proteinTarget: 175,
  carbsTarget: 230,
  fatsTarget: 68,
  waterTargetMl: 3200,
  waterCurrentMl: 2200,
};

export const initialMealLogs: MealEntry[] = [
  {
    id: 'm-1',
    mealType: 'breakfast',
    title: 'Avocado Sourdough Toast & Soft Boiled Eggs',
    calories: 490,
    protein: 26,
    carbs: 48,
    fats: 22,
    fiber: 9,
    timestamp: '08:15 AM',
    healthScore: 92,
    healthScoreReason: 'High monounsaturated fats, bioavailable egg choline, and complex carbohydrates.',
    dietaryTags: ['High Protein', 'Heart Healthy'],
    ingredients: [
      { name: 'Organic Sourdough Bread (2 slices)', estimatedGrams: 80, calories: 190 },
      { name: 'Pasture-raised Eggs (2)', estimatedGrams: 100, calories: 140 },
      { name: 'Fresh Hass Avocado (half)', estimatedGrams: 70, calories: 120 },
      { name: 'Chili flakes & olive drizzle', estimatedGrams: 5, calories: 40 },
    ],
  },
  {
    id: 'm-2',
    mealType: 'lunch',
    title: 'Grilled Salmon Quinoa Bowl with Steamed Asparagus',
    calories: 640,
    protein: 48,
    carbs: 56,
    fats: 24,
    fiber: 8,
    timestamp: '01:30 PM',
    healthScore: 96,
    healthScoreReason: 'Exceptional omega-3 EPA/DHA content and complete amino acid profile from quinoa and salmon.',
    dietaryTags: ['Omega-3 Rich', 'Gluten-Free', 'High Protein'],
    ingredients: [
      { name: 'Wild Atlantic Salmon fillet', estimatedGrams: 200, calories: 340 },
      { name: 'Tri-color Quinoa', estimatedGrams: 140, calories: 180 },
      { name: 'Asparagus spears', estimatedGrams: 80, calories: 35 },
      { name: 'Tahinil-lemon dressing', estimatedGrams: 15, calories: 85 },
    ],
  },
];

export const initialWorkouts: WorkoutLog[] = [
  {
    id: 'w-1',
    title: 'Push Hypertrophy & Chest Power',
    category: 'strength',
    date: 'Today, 07:00 AM',
    durationMinutes: 58,
    caloriesBurned: 440,
    avgHeartRate: 138,
    prsAchieved: ['Incline Barbell Bench 90kg x 6'],
    notes: 'Pushed last set to failure on incline bench. Great pectoral activation and triceps pump.',
    exercises: [
      {
        id: 'e-1',
        name: 'Barbell Flat Bench Press',
        muscleGroup: 'Chest',
        category: 'strength',
        sets: [
          { id: 's-1', setNumber: 1, reps: 10, weightKg: 80, completed: true, rpe: 7 },
          { id: 's-2', setNumber: 2, reps: 8, weightKg: 90, completed: true, rpe: 8 },
          { id: 's-3', setNumber: 3, reps: 6, weightKg: 100, completed: true, rpe: 9, isPR: false },
          { id: 's-4', setNumber: 4, reps: 5, weightKg: 102.5, completed: true, rpe: 9.5, isPR: true },
        ],
      },
      {
        id: 'e-2',
        name: 'Incline Dumbbell Press',
        muscleGroup: 'Upper Chest',
        category: 'strength',
        sets: [
          { id: 's-5', setNumber: 1, reps: 12, weightKg: 32, completed: true, rpe: 8 },
          { id: 's-6', setNumber: 2, reps: 10, weightKg: 34, completed: true, rpe: 8.5 },
          { id: 's-7', setNumber: 3, reps: 8, weightKg: 36, completed: true, rpe: 9 },
        ],
      },
      {
        id: 'e-3',
        name: 'Cable Overhead Triceps Extension',
        muscleGroup: 'Triceps',
        category: 'strength',
        sets: [
          { id: 's-8', setNumber: 1, reps: 15, weightKg: 27.5, completed: true },
          { id: 's-9', setNumber: 2, reps: 12, weightKg: 32, completed: true },
          { id: 's-10', setNumber: 3, reps: 12, weightKg: 32, completed: true },
        ],
      },
    ],
  },
  {
    id: 'w-2',
    title: 'Zone 2 Aerobic Base & Tempo Finisher',
    category: 'cardio',
    date: 'Yesterday, 06:15 PM',
    durationMinutes: 45,
    caloriesBurned: 510,
    avgHeartRate: 142,
    prsAchieved: ['Fastest 5k Split: 22:40'],
    notes: 'Kept heart rate steady in 135-145 Zone 2 corridor, then kicked final 1km at 3:45/km pace.',
    exercises: [
      {
        id: 'e-4',
        name: 'Outdoor Trail Run',
        muscleGroup: 'Full Body Cardio',
        category: 'cardio',
        sets: [],
        cardioStats: {
          distanceKm: 8.2,
          durationMinutes: 45,
          avgSpeedKmh: 10.9,
          avgHeartRate: 142,
        },
      },
    ],
  },
];

export const initialBiometrics: BiometricState = {
  isConnected: false,
  isSimulated: true,
  deviceName: 'PulseWear BLE Pro (Simulated)',
  currentBpm: 72,
  restingBpm: 58,
  hrvMs: 64,
  maxBpmToday: 172,
  avgBpmToday: 76,
  recoveryScore: 89,
  strainScore: 14.8,
  sleepHours: 7.8,
  sleepQuality: 'Deep Restorative',
  timeInZones: {
    z1: 24,
    z2: 38,
    z3: 16,
    z4: 8,
    z5: 2,
  },
};

export const initialCommunityPosts: CommunityPost[] = [
  {
    id: 'cp-1',
    authorName: 'Elena Rostova',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80',
    authorHandle: '@elena_lifts',
    timeAgo: '2h ago',
    category: 'achievement',
    badgeTitle: '🏆 New Personal Record: 120kg Deadlift',
    content: 'Hit a major milestone today! After 6 weeks of dedicated 5x5 programming and focusing on hip hinge cues, I finally pulled 120kg for a clean double without form breakdown. Biometric readiness was 91% this morning—listen to your recovery scores!',
    tags: ['#PRBreakthrough', '#DeadliftClub', '#Powerlifting', '#RecoveryWins'],
    metricsHighlight: {
      label: '1RM Increase',
      value: '+10 kg (+9.1%)',
    },
    likes: 42,
    cheers: 19,
    comments: [
      {
        id: 'cm-1',
        authorName: 'Marcus Chen',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80',
        content: 'Lockout looked rock solid! Outstanding progress Elena.',
        timeAgo: '1h ago',
      },
      {
        id: 'cm-2',
        authorName: 'Sarah Jenkins',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80',
        content: 'Form was pristine. Keep that momentum going for the 130kg!',
        timeAgo: '35m ago',
      },
    ],
  },
  {
    id: 'cp-2',
    authorName: 'David Miller',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80',
    authorHandle: '@miller_endurance',
    timeAgo: '5h ago',
    category: 'workout',
    badgeTitle: '⚡ 21.1k Half-Marathon Training Run',
    content: 'Sunday long run in the books. Kept average HR strictly at 141 bpm (Zone 2). Managed 1h 44m total duration with steady negative splits. Used the AI food scanner yesterday to dial in 350g carb-loading with sweet potatoes and rice bowls!',
    tags: ['#HalfMarathon', '#Zone2Training', '#Endurance', '#CarbLoading'],
    metricsHighlight: {
      label: 'Avg Pace',
      value: '4:56 /km',
    },
    likes: 31,
    cheers: 14,
    comments: [
      {
        id: 'cm-3',
        authorName: 'Coach Leo',
        authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80',
        content: 'Discipline in Zone 2 is what builds the aerobic engine. Textbook execution.',
        timeAgo: '3h ago',
      },
    ],
  },
  {
    id: 'cp-3',
    authorName: 'Aria Patel',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=160&q=80',
    authorHandle: '@aria_nutrifit',
    timeAgo: '1d ago',
    category: 'nutrition',
    badgeTitle: '🥗 Meal Prep Master & Calorie Accuracy',
    content: 'Snapped my week lunch preps with the AI meal camera: 42g protein, 52g carbs, 14g fats with turmeric roasted chicken and wild grains. The micronutrient estimate highlighted high folate & magnesium which matches my high strain week.',
    tags: ['#CleanEating', '#MealPrep', '#HighProtein', '#NutrientDense'],
    metricsHighlight: {
      label: 'Health Score',
      value: '98 / 100',
    },
    likes: 54,
    cheers: 22,
    comments: [],
  },
];

export const initialFitnessGoals: FitnessGoal[] = [
  {
    id: 'g-1',
    title: 'Barbell Back Squat 140 kg',
    category: 'strength',
    currentValue: 125,
    targetValue: 140,
    unit: 'kg',
    deadline: 'In 4 weeks',
  },
  {
    id: 'g-2',
    title: 'Monthly Running Distance',
    category: 'cardio',
    currentValue: 68.4,
    targetValue: 100,
    unit: 'km',
    deadline: 'End of Month',
  },
  {
    id: 'g-3',
    title: 'Daily Protein Consistency (170g+)',
    category: 'nutrition',
    currentValue: 6,
    targetValue: 7,
    unit: 'days/wk',
    deadline: 'Weekly Goal',
  },
];
